AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
# enable rspec extension
require:
  - rubocop-rspec
RSpec/ExampleLength:
  Max: 20
RSpec/MultipleExpectations:
  Max: 10
Metrics/MethodLength:
  Max: 20
RSpec/MultipleMemoizedHelpers:
  Max: 10